---
title: "Data Cleaning"
author: "Nandini Kodali"
format:
    html: 
        code-fold: true
---

{{< include DataCleaning.qmd >}}

# Data Cleaning

Provide the source code used for this section of the project here.

If you're using a package for code organization, you can import it at this point. However, make sure that the **actual workflow steps**—including data processing, analysis, and other key tasks—are conducted and clearly demonstrated on this page. The goal is to show the technical flow of your project, highlighting how the code is executed to achieve your results.

If relevant, link to additional documentation or external references that explain any complex components. This section should give readers a clear view of how the project is implemented from a technical perspective.

Remember, this page is a technical narrative, NOT just a notebook with a collection of code cells, include in-line Prose, to describe what is going on.

## Required Libraries

In [17]:
import os
import json
import re
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nandinikodali/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## News Data

In [ ]:
# load English stop words
stop_words = set(stopwords.words('english'))

def string_cleaner(input_string):
    try:
        # remove unwanted punctuation
        out = re.sub(r"[.,;@#?!&$-]+", " ", input_string) 
        
        # remove escape characters 
        out = re.sub(r'\\u[0-9a-fA-F]{4}', '', out)
        
        # remove extra whitespace
        out = re.sub(r'\s+', ' ', out).strip()
        
        # convert to lowercase
        out = out.lower()
        
        # tokenization
        words = out.split()
        # remove stop words and words of length <= 3
        words = [word for word in words if len(word) > 3 and word not in stop_words]
        
        # join words back into a single string
        out = ' '.join(words)
        
    except Exception as e:
        print(f"Error cleaning string: {e}")
        out = ''
    
    return out

In [45]:
# Function to clean news data
def clean_news_data(raw_data_dir, clean_data_dir):
    
    # Iterate through raw data files
    for file_name in os.listdir(raw_data_dir):
        # Process only raw data files
        if file_name.endswith("_raw_text.json"):  
            
            # Load the raw data
            raw_file_path = os.path.join(raw_data_dir, file_name)
            with open(raw_file_path, 'r') as raw_file:
                raw_data = json.load(raw_file)
            
            # inititlize dictionary to store clean the data
            clean_data = {}
            for article in raw_data:
                # extract title
                title = article.get('title', '')
                # extract article's description
                description = article.get('description', '')
                
                # clean the title and description
                if title and description:
                    # clean the title
                    clean_title = string_cleaner(title)
                    # clean the description
                    clean_description = string_cleaner(description)
                    # store the clean data in the dictionary
                    clean_data[clean_title] = clean_description
            
            # Save the cleaned data to a new file
            clean_file_name = file_name.replace("_raw_text.json", "_clean_news.json")
            clean_file_path = os.path.join(clean_data_dir, clean_file_name)
            with open(clean_file_path, 'w') as clean_file:
                json.dump(clean_data, clean_file, indent=4)

In [46]:
# define directories

# directory with raw data files
raw_data_dir = "../../data/raw-data/News_Drivers"  

# directory for cleaned data files
clean_data_dir = "../../data/processed-data/News_drivers"

In [47]:
# call the function to process the clean data
clean_news_data(raw_data_dir, clean_data_dir)

In [10]:
# raw data
print("RAW DATA---")
raw = "../../data/raw-data/News_drivers/Alonso_raw_text.json"
with open(raw, 'r') as json_file:
    data = json.load(json_file)
for entry in data[:2]:  
    title = entry.get("title", "No Title")
    description = entry.get("description", "No Description")
    print(title,":",description)

print("\n")

# clean data
print("CLEAN DATA---")
clean = "../../data/processed-data/News_drivers/Alonso_clean_news.json"
with open(clean, 'r') as json_file:
    data = json.load(json_file)

for key, value in list(data.items())[:2]: 
    print(key,":", value)

RAW DATA---
Norris calls Verstappen 'dangerous' as Sainz wins in Mexico : Lando Norris cuts Max Verstappen’s lead to 47 points and labels his rival “dangerous” as the championship battle reaches boiling point at the Mexico City Grand Prix.
How well do you know Fernando Alonso? : As he prepares for his 400th F1 grand prix in Mexico City this weekend, find out how much you know about Fernando Alonso.


CLEAN DATA---
norris calls verstappen 'dangerous' sainz wins mexico : lando norris cuts verstappens lead points labels rival dangerous championship battle reaches boiling point mexico city grand prix
well know fernando alonso : prepares grand prix mexico city weekend find much know fernando alonso

## Drivers Standings

In [12]:
input_file = "../../data/raw-data/Driver_standings/driver_standings_2000_2023.json"
output_file = "../../data/processed-data/driver_standings_2000_2023.csv"

In [13]:
with open(input_file, 'r') as f:
    data = json.load(f)

# initialize a list to store extracted records
cleaned_data = []

# loop through each season in the JSON
for season, season_data in data.items():
    # navigate to the StandingsLists section 
    standings_lists = season_data.get('MRData', {}).get('StandingsTable', {}).get('StandingsLists', [])
    
    # loop through each standings entry
    for standings in standings_lists:
        # extract driver standings
        driver_standings = standings.get('DriverStandings', [])
        
        # loop through each entry
        for entry in driver_standings:
            # Extract required fields
            position = entry.get('position', '')            # positions in the standings
            points = entry.get('points', '')                # points earned by the driver
            wins = entry.get('wins', '')                    # number of wins by the driver
            driver = entry.get('Driver', {})                # nested dict. containing driver info
            constructors = entry.get('Constructors', [])    # team info of the driver
            
            # extract driver and constructor details
            given_name = driver.get('givenName', '')
            family_name = driver.get('familyName', '')
            constructor_id = constructors[0].get('constructorId', '') if constructors else ''
            constructor_name = constructors[0].get('name', '') if constructors else ''
            
            # append the record to the cleaned data list
            cleaned_data.append({
                "Season": season,
                "Position": position,
                "FirstName": given_name,
                "LastName": family_name,
                "Constructor_ID": constructor_id,
                "Constructor_Name": constructor_name,
                "Points": points,
                "Wins": wins
            })

In [15]:
# convert the cleaned data into a dataframe for easier manipulation
df = pd.DataFrame(cleaned_data)
df.head()

,Season,Position,FirstName,LastName,Constructor_ID,Constructor_Name,Points,Wins
0,2000,1,Michael,Schumacher,ferrari,Ferrari,108,9
1,2000,2,Mika,Häkkinen,mclaren,McLaren,89,4
2,2000,3,David,Coulthard,mclaren,McLaren,73,3
3,2000,4,Rubens,Barrichello,ferrari,Ferrari,62,1
4,2000,5,Ralf,Schumacher,williams,Williams,24,0

In [16]:
# check for missing values
df.isnull().sum()

Season              0
Position            0
FirstName           0
LastName            0
Constructor_ID      0
Constructor_Name    0
Points              0
Wins                0
dtype: int64

In [ ]:
# concat FirstName and LastName
df['driverName'] = df['FirstName'] + " " + df['LastName']
df = df.drop(['FirstName', 'LastName'], axis=1)

# write the clean data to a new csv file
df.to_csv(output_file, index=False)

## Circuit Information

In [21]:
input_file = "../../data/raw-data/circuit_data/circuit_data.json"
output_file = "../../data/processed-data/circuit_data_clean.csv"

In [22]:
os.makedirs(os.path.dirname(output_file), exist_ok=True)

# read the JSON file
with open(input_file, 'r') as f:
    data = json.load(f)

# extract circuit data
circuits = data.get('MRData', {}).get('CircuitTable', {}).get('Circuits', [])

# prepare a list to store extracted records
cleaned_data = []

for circuit in circuits:
    circuit_id = circuit.get('circuitId', '')
    circuit_name = circuit.get('circuitName', '')
    country = circuit.get('Location', {}).get('country', '')
    latitude = circuit.get('Location', {}).get('lat', '')
    longitude = circuit.get('Location', {}).get('long', '')
    
    # append to the list
    cleaned_data.append({
        "Circuit_ID": circuit_id,
        "Circuit_Name": circuit_name,
        "Country": country,
        "Latitude": latitude,
        "Longitude": longitude
    })

# convert the list to a Pandas DataFrame
df = pd.DataFrame(cleaned_data)

In [23]:
df.head()

    Circuit_ID                    Circuit_Name    Country  Latitude Longitude
0     adelaide         Adelaide Street Circuit  Australia  -34.9272   138.617
1     ain-diab                        Ain Diab    Morocco   33.5786   -7.6875
2      aintree                         Aintree         UK   53.4769  -2.94056
3  albert_park  Albert Park Grand Prix Circuit  Australia  -37.8497   144.968
4     americas         Circuit of the Americas        USA   30.1328  -97.6411

In [24]:
# check for null values
df.isnull().sum()

Circuit_ID      0
Circuit_Name    0
Country         0
Latitude        0
Longitude       0
dtype: int64

In [ ]:
# Save the DataFrame to a CSV file
df.to_csv(output_file, index=False)

## Race data

In [25]:
## Cleaning all the race_data and appending them in to a single csv file 

# input output directory
input_dir = "../../data/raw-data/"
# output directory
output_file = "../../data/processed-data/all_race_results_cleaned.csv"

# creating an output file
os.makedirs(os.path.dirname(output_file), exist_ok=True)

# initialize a list to hold all results
all_combined_results = []

# process each JSON file in the input directory
# they are the only .json files in the directory
for file_name in os.listdir(input_dir):
    # process only JSON files
    if file_name.endswith(".json"): 
        file_path = os.path.join(input_dir, file_name)
        #print(f"Processing file: {file_path}")
        
        # read the JSON file
        with open(file_path, 'r') as f:
            data = json.load(f)
        
        # extract races from the JSON
        races = data.get('MRData', {}).get('RaceTable', {}).get('Races', [])
        
        # prepare a list to hold flattened race results for this file
        file_results = []

        # loop through each race and flatten its data
        for race in races:
            # extract required information 
            race_info = { 
                "season": race.get("season", ""),
                "round": race.get("round", ""),
                "raceName": race.get("raceName", ""),
                "url": race.get("url",""),
                "circuitName": race.get("Circuit", {}).get("circuitName", ""),
                "locality": race.get("Circuit", {}).get("Location", {}).get("locality", ""),
                "country": race.get("Circuit", {}).get("Location", {}).get("country", ""),
                "lat": race.get("Circuit", {}).get("Location", {}).get("lat", ""),
                "long": race.get("Circuit", {}).get("Location", {}).get("long", ""),
                "date": race.get("date", ""),
            }
            
            # extract results and combine with useful details
            results = race.get("Results", [])
            for result in results:
                # combine race-level and result-level data
                combined_data = {**race_info, **result}
                # add flattened driver and constructor details
                combined_data.update({
                    "driverId": result.get("Driver", {}).get("driverId", ""),
                    "driverGivenName": result.get("Driver", {}).get("givenName", ""),
                    "driverFamilyName": result.get("Driver", {}).get("familyName", ""),
                    "constructorId": result.get("Constructor", {}).get("constructorId", ""),
                    "constructorName": result.get("Constructor", {}).get("name", ""),
                    "status": result.get("status", ""),
                    "timeMillis": result.get("Time", {}).get("millis", ""),
                    "time": result.get("Time", {}).get("time", "")
                })
                file_results.append(combined_data)

        # append the results for this file to the combined list
        all_combined_results.extend(file_results)

# aonvert the combined results to a Pandas DataFrame
df = pd.DataFrame(all_combined_results)

In [26]:
df.head()

,season,round,raceName,url,circuitName,locality,country,lat,long,date,...,status,Time,FastestLap,driverId,driverGivenName,driverFamilyName,constructorId,constructorName,timeMillis,time
0,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,Finished,"{'millis': '5960396', 'time': '1:39:20.396'}","{'rank': '1', 'lap': '45', 'Time': {'time': '1...",alonso,Fernando,Alonso,ferrari,Ferrari,5960396,1:39:20.396
1,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,Finished,"{'millis': '5976495', 'time': '+16.099'}","{'rank': '5', 'lap': '38', 'Time': {'time': '1...",massa,Felipe,Massa,ferrari,Ferrari,5976495,+16.099
2,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,Finished,"{'millis': '5983578', 'time': '+23.182'}","{'rank': '4', 'lap': '42', 'Time': {'time': '1...",hamilton,Lewis,Hamilton,mclaren,McLaren,5983578,+23.182
3,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,Finished,"{'millis': '5999195', 'time': '+38.799'}","{'rank': '12', 'lap': '32', 'Time': {'time': '...",vettel,Sebastian,Vettel,red_bull,Red Bull,5999195,+38.799
4,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,Finished,"{'millis': '6000609', 'time': '+40.213'}","{'rank': '13', 'lap': '45', 'Time': {'time': '...",rosberg,Nico,Rosberg,mercedes,Mercedes,6000609,+40.213

In [ ]:
# save the combined DataFrame to a CSV file
df.to_csv(output_file, index=False)

## Weather Data

In [37]:
weather_df = pd.read_csv("../../data/raw-data/weather/race_data_with_weather.csv")

In [38]:
weather_df.isnull().sum()

season      0
raceName    0
url         0
weather     0
dtype: int64

In [39]:
weather_df['weather']

0                                                  Sunny
1                      Overcast with light rain at start
2                                     Mainly cloudy, dry
3                                           Cloudy, rain
4                                     Mainly cloudy, dry
                             ...
117    Sunny with temperatures reaching up to 27 °C (...
118    Dry start, with heavy rain and thunderstorm/mo...
119                                                 Rain
120                                                Sunny
121                                          Warm, Sunny
Name: weather, Length: 122, dtype: object

we will try to categorise the weather description into one of the following categories:

1. Sunny
2. Cloudy
3. Rainy
4. Windy

In [40]:
def classify_weather(weather_description):

    weather_description = weather_description.lower()
    
    if "sunny" in weather_description or "fine" in weather_description or "clear" in weather_description or "dry" in weather_description:
        return "Sunny"
    elif "cloudy" in weather_description or "overcast" in weather_description or "cloud" in weather_description:
        return "Cloudy"
    elif "rain" in weather_description or "thunderstorms" in weather_description or "drizzle" in weather_description:
        return "Rainy"
    elif "windy" in weather_description:
        return "Windy"
    # If no match, classify as "Not Available"
    else:
        return "Not Available"

In [41]:
# call classify_weather()
weather_df['weather_class'] = weather_df['weather'].apply(classify_weather)

In [42]:
weather_df['weather_class'].value_counts()

weather_class
Sunny            95
Cloudy           24
Rainy             2
Not Available     1
Name: count, dtype: int64

Due to severe class imbalance, `weather_class` feature is not a suitable candidate for effective analysis or model training.

In [43]:
print(weather_df[weather_df['weather_class'] == "Not Available"])

   season             raceName  \
9    2006  European Grand Prix

                                                 url        weather  \
9  http://en.wikipedia.org/wiki/2006_European_Gra...  Not Available

   weather_class
9  Not Available

The weather data for 2006 European Grand Prix is not available on wikipedia.

- Using longitude, latitude and the date: The weather was `Sunny`

In [44]:
weather_df['weather_class'] = weather_df['weather_class'].replace('Not Available', 'Sunny')

In [73]:
# Save the updated DataFrame to a CSV file
output_csv = "../../data/processed-data/classified_weather_data.csv"
weather_df.to_csv(output_csv, index=False)

## Race Info Merged

In [75]:
# merge race results and weather information
race_df = pd.read_csv("../../data/processed-data/all_race_results_cleaned.csv")
weather_df = pd.read_csv("../../data/processed-data/classified_weather_data.csv")

# the url contains the season and the race name 
# url can be used to merge the data
merged_df = race_df.merge(weather_df[['url','weather_class']], on='url', how='left')

merged_df.to_csv("../../data/processed-data/race_weather_merged.csv", index=False)

In [33]:
main_df = pd.read_csv("../../data/processed-data/race_weather_merged.csv")
main_df.head()

,season,round,raceName,url,circuitName,locality,country,lat,long,date,...,Time,FastestLap,driverId,driverGivenName,driverFamilyName,constructorId,constructorName,timeMillis,time,weather_class
0,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,"{'millis': '5960396', 'time': '1:39:20.396'}","{'rank': '1', 'lap': '45', 'Time': {'time': '1...",alonso,Fernando,Alonso,ferrari,Ferrari,5960396.0,1:39:20.396,Sunny
1,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,"{'millis': '5976495', 'time': '+16.099'}","{'rank': '5', 'lap': '38', 'Time': {'time': '1...",massa,Felipe,Massa,ferrari,Ferrari,5976495.0,+16.099,Sunny
2,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,"{'millis': '5983578', 'time': '+23.182'}","{'rank': '4', 'lap': '42', 'Time': {'time': '1...",hamilton,Lewis,Hamilton,mclaren,McLaren,5983578.0,+23.182,Sunny
3,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,"{'millis': '5999195', 'time': '+38.799'}","{'rank': '12', 'lap': '32', 'Time': {'time': '...",vettel,Sebastian,Vettel,red_bull,Red Bull,5999195.0,+38.799,Sunny
4,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,2010-03-14,...,"{'millis': '6000609', 'time': '+40.213'}","{'rank': '13', 'lap': '45', 'Time': {'time': '...",rosberg,Nico,Rosberg,mercedes,Mercedes,6000609.0,+40.213,Sunny

In [34]:
main_df.columns

Index(['season', 'round', 'raceName', 'url', 'circuitName', 'locality',
       'country', 'lat', 'long', 'date', 'number', 'position', 'positionText',
       'points', 'Driver', 'Constructor', 'grid', 'laps', 'status', 'Time',
       'FastestLap', 'driverId', 'driverGivenName', 'driverFamilyName',
       'constructorId', 'constructorName', 'timeMillis', 'time',
       'weather_class'],
      dtype='object')

In [35]:
# drop un-needed columns
main_df = main_df.drop(['lat', 'long', 'number', 'positionText', 'Driver', 'Constructor', 'Time', 'FastestLap'], axis=1)

In [36]:
main_df.columns

Index(['season', 'round', 'raceName', 'url', 'circuitName', 'locality',
       'country', 'date', 'position', 'points', 'grid', 'laps', 'status',
       'driverId', 'driverGivenName', 'driverFamilyName', 'constructorId',
       'constructorName', 'timeMillis', 'time', 'weather_class'],
      dtype='object')

In [37]:
main_df.isnull().sum()

season                 0
round                  0
raceName               0
url                    0
circuitName            0
locality               0
country                0
date                   0
position               0
points                 0
grid                   0
laps                   0
status                 0
driverId               0
driverGivenName        0
driverFamilyName       0
constructorId          0
constructorName        0
timeMillis          1291
time                1291
weather_class          0
dtype: int64

The missing values in '`timeMillis'` and '`time'` columns are of those drivers who did not finish the race. Therefore, we will drop these columns and try to analyse the performance based on other metrics.

In [38]:
# drop un-needed columns
main_df = main_df.drop(['timeMillis', 'time'], axis=1)

In [39]:
main_df['constructorName'].value_counts()

constructorName
Ferrari           235
McLaren           234
Williams          229
Red Bull          184
Renault           142
Sauber            139
Mercedes          134
Toro Rosso        127
Force India       100
Haas F1 Team       79
Toyota             76
Jordan             57
BAR                56
Minardi            54
Alfa Romeo         50
Jaguar             45
BMW Sauber         40
AlphaTauri         40
Lotus F1           38
Alpine F1 Team     30
Aston Martin       30
Honda              28
Arrows             26
HRT                24
Marussia           24
Super Aguri        24
Caterham           24
Racing Point       20
Prost              18
Benetton           18
Virgin             16
Manor Marussia     16
Lotus              16
Brawn              10
MF1                 9
Spyker              8
Name: count, dtype: int64

In [40]:
main_df = main_df.drop(['constructorId'], axis=1)

Some of the team names were changed in the process of rebranding or due to a change in ownership. 
For accurate analysis, we will replace the older versions of the constructors' names with the current ones.

- Ferrari 
- McLaren
- Jaguar 
- Williams 
- Sauber $\rightarrow$ BMW Sauber $\rightarrow$ Sauber $\rightarrow$ Alfa Romeo $\rightarrow$ Sauber
- BAR $\rightarrow$ Honda $\rightarrow$ Brawn $\rightarrow$ Mercedes
- Benetton $\rightarrow$ Renault $\rightarrow$ Lotus F1 $\rightarrow$ Renault $\rightarrow$ Alpine
- Jordan $\rightarrow$ Midland $\rightarrow$ Spyker $\rightarrow$ Force India $\rightarrow$ Aston Martin 
- Minardi $\rightarrow$ Toro Rosso $\rightarrow$ Scuderia AlphaTauri
- Haas 
- Toyota
- Virgin Racing $\rightarrow$ Marussia F1 $\rightarrow$ Manor Marussia
- Lotus $\rightarrow$ Caterham
- Arrows
- Super Aguri
- HRT
- Prost

In [41]:
constructor_mapping= {
    "Jaguar" : "Red Bull",
    "BMW Sauber" : "Sauber",
    "Alfa Romeo" : "Sauber",
    "BAR" : "Mercedes",
    "Honda" : "Mercedes",
    "Brawn" : "Mercedes",
    "Minardi" : "AlphaTauri",
    "Toro Rosso" : "AlphaTauri",
    "Force India" : "Aston Martin",
    "Jordan" : "Aston Martin",
    "Racing Point" : "Aston Martin",
    "MF1" : "Aston Martin",
    "Spyker" : "Aston Martin",
    "Lotus F1" : "Alpine F1 Team",
    "Renault" : "Alpine F1 Team",
    "Benetton" : "Alpine F1 Team",
    "Manor Marussia" : "Marussia",
    "Virgin" : "Marussia",
    "Lotus" : "Caterham",

}

In [42]:
main_df['constructorName'] = main_df['constructorName'].replace(constructor_mapping)

In [43]:
main_df['constructorName'].value_counts()

constructorName
Ferrari           235
McLaren           234
Red Bull          229
Williams          229
Sauber            229
Mercedes          228
Alpine F1 Team    228
Aston Martin      224
AlphaTauri        221
Haas F1 Team       79
Toyota             76
Marussia           56
Caterham           40
Arrows             26
Super Aguri        24
HRT                24
Prost              18
Name: count, dtype: int64

In [44]:
main_df['driverName'] = main_df['driverGivenName'] + " " + main_df['driverFamilyName']

In [45]:
main_df = main_df.drop(['driverGivenName','driverFamilyName'], axis = 1)

In [46]:
main_df.head(2)

,season,round,raceName,url,circuitName,locality,country,date,position,points,grid,laps,status,driverId,constructorName,weather_class,driverName
0,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,2010-03-14,1,25.0,3,49,Finished,alonso,Ferrari,Sunny,Fernando Alonso
1,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,2010-03-14,2,18.0,2,49,Finished,massa,Ferrari,Sunny,Felipe Massa

Classify the satus column in to broader categories. This column provides information on whether the driver has finished the race or not, if not, was it because of a mechanical failure, an accident, or was he lapped. 
The categories are:

- Finished
- Lap
- Accident
- Mechanical
  
Grouping the data helps understand the major reasons for the race results without getting overwhelmed by the granular details.

In [47]:
main_df['status'].unique()

array(['Finished', '+1 Lap', '+2 Laps', 'Electrical', 'Hydraulics',
       'Overheating', 'Gearbox', 'Suspension', 'Accident', '+5 Laps',
       'Wheel', 'Engine', 'Spun off', 'Collision', '+3 Laps', '+4 Laps',
       '+10 Laps', 'Throttle', 'Clutch', 'Technical', 'Mechanical',
       'Driveshaft', 'Transmission', 'Steering', 'Puncture', 'Brakes',
       'Retired', 'Tyre', 'Fuel pressure', '+9 Laps', 'Water leak',
       'Disqualified', 'Did not qualify', '+42 Laps', 'Engine misfire',
       'Power Unit', 'Oil pressure', 'Safety concerns', 'Fuel system',
       '+6 Laps', 'Electronics', 'Collision damage', 'Wheel nut',
       'Battery', 'Oil leak', '+7 Laps', 'Stalled', 'Exhaust',
       'Vibrations', 'Broken wing', 'Fuel', 'Wheel rim', 'Power loss',
       '107% Rule', '+8 Laps', 'ERS', 'Withdrew', 'Cooling system',
       'Water pump', 'Fuel leak', 'Front wing', 'Turbo', 'Damage',
       'Out of fuel', 'Radiator', 'Oil line', 'Fuel rig',
       'Launch control', 'Not classified', 'Pneumatics', 'Differential'],
      dtype=object)

In [48]:
# classifying different categories under status
def classify_status(status):
    if status == 'Finished':
        return 'Finished'
    # if the status contains the word 'Lap' 
    elif 'Lap' in status:  
        return 'Lapped'
    elif status in ['Accident', 'Collision', 'Spun off', 'Withdrew']:
        return 'Accident'
    # all other statuses are classified as 'Mechanical'
    else:
        return 'Mechanical'

main_df['status'] = main_df['status'].apply(classify_status)

In [49]:
main_df['status'].value_counts()

status
Finished      1105
Lapped         693
Mechanical     412
Accident       190
Name: count, dtype: int64

In [50]:
main_df.to_csv("../../data/processed-data/race_info.csv", index=False)

Finish category - new categorical variable

In F1, race outcomes are categorized based on finishing positions:

- The top 3 finishers are celebrated on the podium and referred to as achieving a **Podium Finish**
- All drivers who finish in top 10 earn championship points, ranging from 25 points for the winner, 18 for second place, and decreasing to 1 point for the 10th position.
- Drivers finishing outside the top 10 do not earn any championship points.

In [ ]:
data = pd.read_csv("../../data/processed-data/race_info.csv")
# create a new categorical variable 
data['FinishCategory'] = ''
# iterate through each row of the dataset
for i in range(len(data)):
    # if the position is 1,2 or 3
    if data['position'][i] in [1,2,3]:
        # assign the category as podium
        data['FinishCategory'][i] = "Podium"
    # if the position is in between 4 and 10
    elif data['position'][i] in [4,5,6,7,8,9,10]:
        # assign the category as points finish
        data['FinishCategory'][i] = "Points Finish"
    # assign no points for poistions outside top 10
    else:
        data['FinishCategory'][i] = "No Points"

In [52]:
data.head()

,season,round,raceName,url,circuitName,locality,country,date,position,points,grid,laps,status,driverId,constructorName,weather_class,driverName,FinishCategory
0,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,2010-03-14,1,25.0,3,49,Finished,alonso,Ferrari,Sunny,Fernando Alonso,Podium
1,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,2010-03-14,2,18.0,2,49,Finished,massa,Ferrari,Sunny,Felipe Massa,Podium
2,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,2010-03-14,3,15.0,4,49,Finished,hamilton,McLaren,Sunny,Lewis Hamilton,Podium
3,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,2010-03-14,4,12.0,1,49,Finished,vettel,Red Bull,Sunny,Sebastian Vettel,Points Finish
4,2010,1,Bahrain Grand Prix,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,Bahrain International Circuit,Sakhir,Bahrain,2010-03-14,5,10.0,5,49,Finished,rosberg,Mercedes,Sunny,Nico Rosberg,Points Finish

In [53]:
data.to_csv("../../data/processed-data/race_info.csv", index=False)

## Race Track Features

In [25]:
# race track features
data = pd.read_csv("../../data/raw-data/circuit_data/merged_circuit_features.csv")
data.head()

,Year,Grand Prix,Track Length (m),Max Speed (km/h),Full Throttle (%),Number of Corners,Number of Straights
0,2020,Pre-Season Test 1,4312.438437,323,70.673953,1,4
1,2020,Pre-Season Test 2,4312.438437,323,70.673953,1,4
2,2020,Austrian Grand Prix,4312.438437,323,70.673953,1,4
3,2020,Styrian Grand Prix,4292.610384,300,46.556886,2,6
4,2020,Hungarian Grand Prix,4348.049386,318,58.114374,0,6

In [26]:
data.isnull().sum()

Year                   0
Grand Prix             0
Track Length (m)       0
Max Speed (km/h)       0
Full Throttle (%)      0
Number of Corners      0
Number of Straights    0
dtype: int64

**Standardization**

Standardization is a preprocessing step used to scale the features is a consistent scale for more accurate and stable modelling. Features with different scales can lead to one feature dominating others during model training, Standardization eliminates disparity. 

For the Race Track Features, `StandardScaler` is used, this standardizes the data by “removing the mean and scaling to unit variance”[^1].

Formula for Standardization:
$$ Z = \frac{X - \mu}{\sigma} $$
where:

- $X$: the original value 
- $\mu$: mean
- $\sigma$: standard deviation of the feature

[^1]: [StandardScaler](https://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [27]:
req_cols = ["Track Length (m)", "Max Speed (km/h)", "Full Throttle (%)","Number of Corners", "Number of Straights"]
scaler = StandardScaler()

# Apply the scaler to the dataframe
data[req_cols] = scaler.fit_transform(data[req_cols])

In [31]:
data.head()

,Year,Grand Prix,Track Length (m),Max Speed (km/h),Full Throttle (%),Number of Corners,Number of Straights
0,2020,Pre-Season Test 1,-1.000607,-0.115670,1.059667,-0.789651,-0.938394
1,2020,Pre-Season Test 2,-1.000607,-0.115670,1.059667,-0.789651,-0.938394
2,2020,Austrian Grand Prix,-1.000607,-0.115670,1.059667,-0.789651,-0.938394
3,2020,Styrian Grand Prix,-1.024865,-1.840980,-1.757479,-0.275003,-0.037811
4,2020,Hungarian Grand Prix,-0.957039,-0.490737,-0.407433,-1.304300,-0.037811

In [32]:
data.to_csv("../../data/processed-data/race_track_features.csv")

## Pitstop data

In [45]:
df = pd.read_csv("../../data/raw-data/pitstop_data.csv")
df.head()

,Year,Round,RaceName,DriverID,Lap,Stop,Time,Duration
0,2011,1,Australian Grand Prix,alguersuari,1,1,17:05:23,26.898
1,2011,1,Australian Grand Prix,michael_schumacher,1,1,17:05:52,25.021
2,2011,1,Australian Grand Prix,webber,11,1,17:20:48,23.426
3,2011,1,Australian Grand Prix,alonso,12,1,17:22:34,23.251
4,2011,1,Australian Grand Prix,massa,13,1,17:24:10,23.842

**Pivoting** involves reshaping data by rearranging rows into columns. It is used to transform long-format data (many rows for each entity) to wide-format (one row per entity with multiple columns).

Here, each `Stop` Number becomes a seperate set of columns, Lap1, Lap2, Duration1, Duration2 and so on.

In [46]:
transformed = (
    # group the data by year, round, race name and driver
    # create Pit stop number for each pitstop of a driver in the data
    # pit stop number will be used for pivoting
    df.assign(PitStopNumber=lambda x: x.groupby(['Year', 'Round', 'RaceName', 'DriverID']).cumcount() + 1)
    # index[] - unique identifiers
    # columns - used to create new columns for each pit stop
    # values - values to be assigned to the new columns in the pivot table
    .pivot(index=['Year', 'Round', 'RaceName', 'DriverID'], columns='PitStopNumber', values=['Lap', 'Stop', 'Time', 'Duration'])
)

# after pivoting, cols have multi-index structure
# combine col name with pit stop number for easier handling
transformed.columns = [f"{col[0]}{col[1]}" for col in transformed.columns]

# reset index to turn it into a DataFrame
transformed.reset_index(inplace=True)

# handling missing values - replace with 0
transformed = transformed.fillna(0)

transformed.head(2)

,Year,Round,RaceName,DriverID,Lap1,Lap2,Lap3,Lap4,Lap5,Lap6,...,Time5,Time6,Time7,Duration1,Duration2,Duration3,Duration4,Duration5,Duration6,Duration7
0,2011,1,Australian Grand Prix,alguersuari,1,17,35,0,0,0,...,0,0,0,26.898,24.463,26.348,0,0,0,0
1,2011,1,Australian Grand Prix,alonso,12,27,42,0,0,0,...,0,0,0,23.251,24.733,24.181,0,0,0,0

In [70]:
transformed.shape

(5118, 32)

**MinMaxx Scaling**: Transforms the fature range by scaling its min and max values. 

Formula:
$$X_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

In [78]:
# convert relevant columns to minutes
from sklearn.preprocessing import MinMaxScaler
def convert_to_minutes(value):
    try:
        # convert seconds to minutes
        return float(value) / 60  
    except:
        # default to 0 for invalid values
        return 0  
# List of time and duration columns
time_and_duration_cols = [
    "Time1", "Time2", "Time3", "Time4", "Time5", "Time6", "Time7",
    "Duration1", "Duration2", "Duration3", "Duration4", "Duration5", "Duration6", "Duration7"
]

# convert each column to minutes
for col in time_and_duration_cols:
    if col in transformed.columns:
        transformed[col] = transformed[col].apply(convert_to_minutes)

# handling missing values - replace with 0
transformed.fillna(0, inplace=True)

# select all columns except `Year`, `Round`, `RaceName`, and `DriverID` for scaling
scalable_columns = transformed.drop(columns=["Year", "Round", "RaceName", "DriverID"]).columns

# apply MinMax scaling
scaler = MinMaxScaler()
transformed[scalable_columns] = scaler.fit_transform(transformed[scalable_columns])

print(transformed.head())

   Year  Round               RaceName     DriverID      Lap1      Lap2  \
0  2011      1  Australian Grand Prix  alguersuari  0.000000  0.229730
1  2011      1  Australian Grand Prix       alonso  0.174603  0.364865
2  2011      1  Australian Grand Prix     ambrosio  0.206349  0.513514
3  2011      1  Australian Grand Prix  barrichello  0.190476  0.310811
4  2011      1  Australian Grand Prix        buemi  0.222222  0.391892

       Lap3      Lap4  Lap5  Lap6  ...  Time5  Time6  Time7  Duration1  \
0  0.479452  0.000000   0.0   0.0  ...    0.0    0.0    0.0   0.453661
1  0.575342  0.000000   0.0   0.0  ...    0.0    0.0    0.0   0.392151
2  0.000000  0.000000   0.0   0.0  ...    0.0    0.0    0.0   0.426017
3  0.383562  0.512821   0.0   0.0  ...    0.0    0.0    0.0   0.398762
4  0.000000  0.000000   0.0   0.0  ...    0.0    0.0    0.0   0.427417

   Duration2  Duration3  Duration4  Duration5  Duration6  Duration7
0   0.428042   0.457423   0.000000        0.0        0.0        0.0
1   0.432766   0.419802   0.000000        0.0        0.0        0.0
2   0.462739   0.000000   0.000000        0.0        0.0        0.0
3   0.662386   0.293259   0.469108        0.0        0.0        0.0
4   0.404192   0.000000   0.000000        0.0        0.0        0.0

[5 rows x 32 columns]

In [79]:
transformed.to_csv("../../data/processed-data/pitstop.csv")

All the clean datasets can be found [here](https://github.com/dsan-5000/project-NandiniKodali988/tree/main/data/processed-data)